# Input paths - these can be overridden via command line
contigs_table: ""  # Default empty, should be provided at runtime
seq_data_dir: ""   # Default empty, should be provided at runtime
base_data_dir: "" # Default empty, should be provided at runtime
workdir: "."       # Working directory for Snakemake

# Analysis parameters
segments:
  - "L"
  - "S"

# Tool-specific parameters
mafft:
  threads: 5

iqtree:
  model: "GTR+F+I+I+R8"
  bootstraps: 1000

# Sequence analysis settings
distance_threshold: 3.0  # Number of standard deviations above the mean to consider as outlier
