name: lasvdedup-env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.9
  - snakemake-minimal=7.32
  - mafft
  - iqtree>=2.1
  - trimal
  - csvtk
  - wget
  - curl
  - pip
  - pip:
    - .
