# Input paths - these can be overridden via command line
CONTIGS_TABLE: ""  # Default empty, should be provided at runtime
SEQ_DATA_DIR: ""   # Default empty, should be provided at runtime
BASE_DATA_DIR: "https://raw.githubusercontent.com/Joon-Klaps/lasvdedup/refs/heads/main/lasvdedup/data/"
OUTDIR: "lasvdedup-out"  # Default output directory
WORKDIR: ".work"       # Working directory for Snakemake
LOGLEVEL: "INFO"

# Parallelization settings
THREADS: 4        # Default threads for the whole pipeline

# Analysis parameters
SPECIES: "LASV"
SEGMENTS: ["L", "S"]

# Tool-specific parameters
MAFFT:
  THREADS: 5

IQTREE:
  MODEL: "GTR+F+R9"
  BOOTSTRAPS: 1000

# Sequence analysis settings
DEDUPLICATE:
  SAMPLE_REGEX: "LVE[0-9]{5}"
  LENGTH_COLUMN: "(annotation) qlen"
  SELECTION_COLUMNS:
    - "(samtools Post-dedup) reads mapped (R1+R2)"
    - "(general_stats) mosdepth 10X coverage"
  THRESHOLDS:
    L:  # L segment
      LOWER: 0.01
      UPPER: 0.02
      CLADE_SIZE: 8
      Z_THRESHOLD: 2
      TARGET_LENGTH: 7200
    S:  # S segment
      LOWER: 0.01
      UPPER: 0.02
      CLADE_SIZE: 8
      Z_THRESHOLD: 2.0
      TARGET_LENGTH: 3400

  # Default thresholds for segments not explicitly defined
  DEFAULT_THRESHOLD:
      LOWER: 0.01
      UPPER: 0.02
      CLADE_SIZE: 8
      Z_THRESHOLD: 2.0
      TARGET_LENGTH: 5000