name: Conda Test

on:
  push:
    branches: [ main, master ]
    paths-ignore:
      - "*.md"
  pull_request:
    branches: [ main, master ]
    paths-ignore:
      - "*.md"


jobs:
  pytest:
    name: Run unit tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        channels: conda-forge,bioconda,defaults

    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda env create -f environment.yml
        conda activate lasvdedup-env
        pip install pytest pytest-mock

    - name: Run tests
      shell: bash -l {0}
      run: |
        conda activate lasvdedup-env
        pytest tests/ -v

  cli-test:
    name: Run CLI tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        channels: conda-forge,bioconda,defaults

    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda env create -f environment.yml
        conda activate lasvdedup-env

    - name: Run CLI tests
      shell: bash -l {0}
      run: |
        conda activate lasvdedup-env
        cd tests/data/
        lasvdedup --input contigs-test.tsv --seq-dir seq_data  --config test-config.yaml --log-level DEBUG