name: Conda Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-conda:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: "3.9"
        channels: conda-forge,bioconda,defaults

    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda env create -f environment.yml
        conda activate lasvdedup-env
        pip install -e .
        pip install pytest pytest-mock

    - name: Run tests
      shell: bash -l {0}
      run: |
        conda activate lasvdedup-env
        pytest tests/
