name: Python Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.x"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-mock
        pip install -e .

    - name: Install bioinformatics dependencies
      run: |
        pip install biopython pandas numpy

    - name: Run tests
      run: |
        pytest tests/

    - name: Test package installation
      run: |
        python -c "import lasvdedup; print(f'Package version: {lasvdedup.__version__}')"
